### PR TITLE
Chapter 2 of Federal Field Guide / Deciding what to buy, Appendix, Download link

### PR DESCRIPTION
**Pull request by cmajel**
This adds 
* the content Chapter 2 of the Federal Field Guide, Deciding what to buy ([design google doc](https://docs.google.com/document/d/1P5034x8YoNj0v1NqxLbqfBApNSgX2m7gO16uLd1TegI/edit?ts=5f4ec0a9#))
* the federal [field guide appendix](https://docs.google.com/document/d/11IIUfXULjpcFERoeFXCQyyJe5zxKnf2CLhwxm6wHWGg/edit?ts=5f4ec0bc#heading=h.nisirc87fzq0)
* placeholder images for each section of the Federal Field Guide
* a PDF download link for the State Field Guide  

A few notes for review or future discussion:
* The `executive summaries` were formatted originally in list form. I've kept them as is, but wondering if these should actually be paragraphs.
* Also noting that there are some multi-paragraph lists that I've kept the doc formatting, but seems a little strange.
Screen Shot 2020-09-03 at 5 10 15 PM
* I updated footnotes that were just urls to include text based link. For example instead of `https://18f.gsa.gov/2018/04/17/so-youre-a-product-owner/` I did `See 18F's <a href="https://18f.gsa.gov/2018/04/17/so-youre-a-product-owner/"> So, you’re a Product Owner...</a> for specifics.`
* Could use eyes on...
1.  this buyer/seller exchange formatting, and if this makes sense
Screen Shot 2020-09-03 at 5 05 25 PM
2. This formatting for a legislation block, and if double pull quotes create accessibility issues. 
Screen Shot 2020-09-03 at 5 07 41 PM

### CODE REVIEW

**Comment by cmajel** [comment]
hmm @igorkorenfeld noticing that the state field guide download link worked for me locally, but is 404ing in the [federalist preview](https://federalist-fe6e9378-2eb1-4eb8-a686-9f9a574a410d.app.cloud.gov/preview/18f/derisking-gov-tech/cb-deciding/state-field-guide/). Do you know how to fix this?

**Comment by igorkorenfeld** [comment]
**Exec Summaries**
That's a good note. In the print version I made them into regular paragraphs if they were every just one bullet, but bulleted if it was truly a list.

**Multi-paragraph**
Great point, this is another area that should probably just be a set of paragraphs. I'll do a second pass once we get the majority of the content up and adjust bullets to paragraphs wherever possible.

**Footnote text**
That's perfect, thank you

👀 
1. I like it! Two ideas that came to mind, what if we bold the speaker roles, and then make one italic and one roman to further distinguish who is talking:
image

2. Ah so nested block quotes would be an accessibility issue? Good catch. I am thinking of two possible ways around it
a. Maybe add a class to one of the paragraphs within the block quote to indent it instead of using a second block quote
b. Make the indented 1 a bullet point or a numbered list instead (but still within the first block quote) 

In the print layout I also styled block quotes in grey and made them slightly smaller font, so that may be another way to show where the block quote starts and ends. 

3. I think I got the PDF thing to work. I had to use a jekyll assets in a new (to me) way. I put added that commit to this branch so we can package it all together.

**Comment by cmajel** [comment]
@igorkorenfeld thanks for the feedback!

1. Added that alternating italics style!

Screen Shot 2020-09-04 at 4 55 36 PM

2. I'm not sure if nested block quotes are an accessibility issue? But it felt likely. I added a class which feels brittle but works for the time being. Maybe we can ask the accessibility guide if it actually is an issue.
Screen Shot 2020-09-04 at 4 57 21 PM

3. Thanks for the link help. 🎉 That seems to work.

**Comment by igorkorenfeld** [comment]
Small USWDS thing on the indent, otherwise this looks great.

**Pull request merged**
