### PR TITLE
Implemented fixes for accessibility

### PR DESCRIPTION
**Pull request by HannaSChang**

### CODE REVIEW

**Review by jskinne3 — APPROVED** [review]
Sensible changes; looks good!

**Review by jskinne3 — APPROVED** [review]

**Comment by HannaSChang** [comment]
@jskinne3 Thanks for approving! For some reason it still wouldn't let me merge so I tried adding you as one of the reviewers but I think I undid your approval by doing so. So sorry but do you mind approving again? Thank you!

**Review by jskinne3 — APPROVED** [review]
Trying again

edit: still does not work! I think I don't have needed permissions to this repository. I'll try asking for them!

**Review by jasnakai — APPROVED** [review]
LGTM!

**Pull request merged**
